#!/usr/bin/env python3
"""Build the skills catalog.

Scans every skill folder, reads its SKILL.md frontmatter (name, description) plus
optional _meta.json, writes index.json, and refreshes the generated table in
README.md. Same role as the plugin marketplace's build_index.py.

Usage:  python build_index.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent
SKIP_DIRS = {".git", "__pycache__", "site"}
README_START = "<!-- BEGIN SKILLS TABLE -->"
README_END = "<!-- END SKILLS TABLE -->"


def _frontmatter(text: str) -> dict:
    """Parse the leading --- ... --- block. Supports simple `key: value` pairs
    with indented continuation lines. No YAML dependency."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    try:
        end = lines.index("---", 1)
    except ValueError:
        return {}
    data, key = {}, None
    for line in lines[1:end]:
        if line[:1] in (" ", "\t") and key:
            data[key] += " " + line.strip()
        elif ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip()
            # YAML block scalars (| > |- >- etc.) carry their text on the
            # following indented lines, so start empty and let those append.
            data[key] = "" if val[:1] in ("|", ">") else val.strip("'\"")
    return {k: v.strip() for k, v in data.items()}


def _skill_md(d: Path):
    for name in ("SKILL.md", "skill.md"):
        p = d / name
        if p.exists():
            return p
    return None


def build() -> dict:
    skills = []
    for d in sorted(ROOT.iterdir()):
        if not d.is_dir() or d.name in SKIP_DIRS or d.name.startswith("."):
            continue
        md = _skill_md(d)
        if md is None:
            continue
        fm = _frontmatter(md.read_text(encoding="utf-8"))
        meta_p = d / "_meta.json"
        meta = json.loads(meta_p.read_text(encoding="utf-8")) if meta_p.exists() else {}

        files = [f for f in d.rglob("*") if f.is_file()]
        skills.append({
            "id": d.name,
            "name": meta.get("displayName") or fm.get("name") or d.name,
            "description": fm.get("description", ""),
            "version": str(meta.get("latest", {}).get("version", "1.0.0")),
            "author": meta.get("owner", ""),
            "entry": md.name,
            "file_count": len(files),
            "size_bytes": sum(f.stat().st_size for f in files),
        })

    index = {"count": len(skills), "skills": sorted(skills, key=lambda s: s["id"])}
    (ROOT / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    _write_readme_table(index)
    return index


def _write_readme_table(index: dict) -> None:
    """Refresh the generated table inside README.md, leaving the prose intact."""
    readme = ROOT / "README.md"
    if not readme.exists():
        return
    text = readme.read_text(encoding="utf-8")
    head, sep, rest = text.partition(README_START)
    if not sep:
        return
    _, sep2, tail = rest.partition(README_END)

    rows = ["| Skill | Description |", "|---|---|"]
    for s in index["skills"]:
        desc = s["description"].replace("|", r"\|")
        if len(desc) > 200:
            desc = desc[:197].rstrip() + "..."
        rows.append("| [`{0}`]({0}/) | {1} |".format(s["id"], desc))

    note = "_{0} skills. Generated by `build_index.py` \u2014 do not edit this table by hand._".format(index["count"])
    block = "\n\n".join([README_START, note, "\n".join(rows), README_END])
    readme.write_text(head + block + (tail if sep2 else ""), encoding="utf-8")


if __name__ == "__main__":
    idx = build()
    print("Indexed {0} skills -> index.json".format(idx["count"]))
    missing = [s["id"] for s in idx["skills"] if not s["description"]]
    if missing:
        print("WARNING: {0} without a description: {1}".format(len(missing), ", ".join(missing)))
